apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-operator.yaml
- grafana-app.yaml
- dashboards
- https://github.com/redhat-appstudio/o11y/config/probes/monitoring/grafana/base?ref=25e16d597036dae42906c932b985277d16874eac
