---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/yftacherzog/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-STONEO11Y-86-apply-prometheus-rules-in-dev
