---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/yftacherzog/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-offboard-o11y-prom-rules
