apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      remoteWrite:
        url: https://observatorium-mst.api.stage.openshift.com/api/metrics/v1/rhtap/api/v1/receive
        oauth2:
          clientId:
            secret:
              key: client_id
              name: rhobs-secret
          clientSecret:
            secret:
              key: client_secret
              name: rhobs-secret
          token_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          endpoint_params:
              audience: observatorium-osd-staging
          write_relabel_configs:
          - source_labels: [__name__]
            regex: "prometheus_target_interval_length_seconds"
            action: keep
