apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - core-config.yaml
components:
  - ../patches/build
  - ../patches/image-controller
  - ../patches/integration
  - ../patches/konflux-info
  - ../patches/konflux-ui
  - ../patches/namespace-lister
  - ../patches/release
