apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=e8847fe60371e36b9f405b67235c9fcfa4a97362
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/redhat-user-workloads/konflux-vanguard-tenant/konflux-operator
    newTag: on-pr-e8847fe60371e36b9f405b67235c9fcfa4a97362
