apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=f1f2d032479eb32c50e0e8da30bfb584f0159127
  - konflux.yaml

patches:
  - path: release-config.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/redhat-user-workloads/konflux-vanguard-tenant/konflux-operator
    newTag: on-pr-f1f2d032479eb32c50e0e8da30bfb584f0159127-linux-x86-64
